# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# HTTP Server
server:
  port: ${PORT:3333}   # HTTP (Tomcat) port
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Carritomicro?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 
  jpa:
    generate-ddl: true
    
