# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# HTTP Server
server:
  port: ${PORT:3333}   # HTTP (Tomcat) port
  
spring:
  datasource:
    url: jdbc:mysql://172.17.0.5:3306/carritomicro?useSSL=false
    username: root
    password: root
  jpa:
    generate-ddl: true
    
